### ISSUE TITLE
Clasificación directorios asignaturas - Discusión

### ISSUE THREAD

**Issue by Delunado** [Stuja/stuja#17]
¿Deberíamos organizar las carpetas de las asignaturas usando subdirectorios?
Ejemplo:
    Primer Curso:
        Primer Cuatrimestre:
            Fundamentos Programación
            ...

Aún faltan muchas asignaturas y cuando haya más se van a acumular, haciendo difícil la búsqueda si no se usa el índice del README.

**Comment by manuelalferez** [comment]
Sí, añadiría más organización. En ese caso, también se debería de actualizar todos las rutas relativas, tanto de los enlaces de `universidad/README.md` como los de las asignaturas específicas. 
Mejor hacerlo ahora que hay poco que modificar, que después que habrá que tocar más rutas.

**Comment by Davavico22** [comment]
He realizado los directorios correspondientes, faltaría por actualizar el archivo `universidad/README.md`
