### ISSUE TITLE
Archivos pesados

### ISSUE THREAD

**Issue by Delunado** [Stuja/stuja#3]
Los archivos pesados (>100mb) no pueden hostearse aquí de forma directa. ¿Qué solución se propone?

**Comment by manuelalferez** [comment]
La [solución que nos da GitHub](https://help.github.com/en/github/managing-large-files). Básicamente pasa por [instalar Git LFS](https://help.github.com/en/github/managing-large-files/installing-git-large-file-storage). 
¿Te funciona?

**Comment by manuelalferez** [comment]
Instalando Git LFS se puede subir archivos de gran tamaño.
