### ISSUE TITLE
Informacion erronea en CONTRIBUIR.md

### ISSUE THREAD

**Issue by Davavico22** [Stuja/stuja#35]
En el tutorial para comenzar a aportar dice que el botón Fork esta arriba a la izquierda, en mi caso está en la derecha.

Revisadlo para confirmarlo y poder cambiarlo

**Comment by manuelalferez** [comment]
Como GitHub está cambiando la estética y redistribuyendo el contenido de su interfaz, sugiero no hacer mención a la posición. Tipo:
![image](https://user-images.githubusercontent.com/38152841/85528365-11a35100-b60c-11ea-8008-9f0661b4d7fd.png)

Y con algún tipo de información adicional. 

Si quieres cambiar a la nueva versión: 

![image](https://user-images.githubusercontent.com/38152841/85528138-dacd3b00-b60b-11ea-8cc8-d0398e17d9db.png)
