### ISSUE TITLE
Añadir guías docentes a cada asignatura

### ISSUE THREAD

**Issue by Delunado** [Stuja/stuja#4]
Sería interesante añadir un enlace en la ficha de cada asignatura a su guía docente, que aporta información interesante e importante sobre la asignatura.

**Comment by manuelalferez** [comment]
Sí, es buena idea. Algunas asignaturas tienen su guía docente actualizada y otras no. Es el caso de [Estructuras de datos](https://uvirtual.ujaen.es/pub/es/informacionacademica/catalogoguiasdocentes/p/2018-19/4/133A/13312012/es/2018-19-13312012_es.html).
Habría que actualizar también la plantilla, README-PARA-ASIGNATURA.md.
