### ISSUE TITLE
Añadir archivo Readme

### ISSUE THREAD

**Issue by Davavico22** [Stuja/stuja#43]
Tras la organización de carpetas, es necesario añadir un archivo readme a cada asignatura.

**Comment by Davavico22** [comment]
Para que se puedan ver los directorios, estos deben de tener algún elemento. Considero que esta tarea tiene mayor prioridad actualmente

**Comment by manuelalferez** [comment]
Gracias @Davavico22!  No se si se debería de categorizar como un issue, porque hasta que nadie aporte con teoría, prácticas y material de apoyo a esas asignaturas el issue va a seguir ocurriendo. 

En un issue que obliga a colaborar en todos las asignatura donde se da el evento. 

Sugiero dejarlo como está y sabiendo que esas son asignaturas sin contenido. 
`Git` está registrando que esas directorios existen, pero `GitHub` no los muestra. 

Abre el hilo si crees que debemos hacer algo al respecto.
